version: 1

customFlows:
  plan:
    steps:
      - name: Run TFLint
        run: |
          echo "Running tflint..."
          tflint --init
          tflint

      - name: Run tfsec
        run: |
          echo "Running tfsec..."
          tfsec .

      - name: Terraform Plan
        run: terraform plan -out=tfplan

  apply:
    steps:
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
