environments:
  infra:
    name: "Infra Deployment"
    templateName: "opentofu"   # or "opentofu" if you’re using tofu
    vcs:
      type: "opentofu"
      repo: "vikitech-tofu-deploy-template-31690"
      path: "infra"